### ISSUE TITLE
Problem sourcing vimrc

### ISSUE THREAD

**Issue by tallysmartins** [rodrigosiqueira/lappis_vimrc#17]
When I execute install and try to source ~/.vimrc  I got the problem message:

bash: /home/tallys/.vimrc: line 4: syntax error near unexpected token `('
bash: /home/tallys/.vimrc: line 4:`" Use Vim settings, rather then Vi settings (much better!).'

If I remove the line (its a comment) I got endless problems on other lines.

Using Linux Mint 17.2 with Cinamon

**Comment by chocoelho** [comment]
You should source your vimrc from within Vim, not in a shell environment ;)

:help source

:so[urce] {file}        Read Ex commands from {file}.  These are 
commands that
                                 start with a ":".
                                 Triggers the SourcePre autocommand.

:so[urce]! {file}       Read Vim commands from {file}.  These are commands
                                 that are executed from Normal mode, 
like you type
them.
                                 When used after :global, :argdo, :windo,
                                 :bufdo, in a loop or when another 
command follows
                                 the display won't be updated while 
executing the
commands.
                                 {not in Vi}
